Created exercitiul 1
SkillBrain-com/Meteor-fe-g1-15-09-2022 pull request #30
Opened 2022-10-16 18:41 UTC by AdrianaGroza

2022-10-17 06:33 UTC, cezarmocanu requested changes
Per total bine, ai dus problemele la capat, dar o sa te rog sa faci modificarile necesare, astfel incat sa iti imbunatatesti intelegerea in legatura cu variabilele

2022-10-17 06:33 UTC, cezarmocanu commented on tema1/script.js
> +var variabila = "a";
aici o sa te rog sa modifici in ```let```, doarece este standardul modern de la javascript spre deosebire de ```var```. 

De asemenea, cand am mentionat declara variabila a, ma refeream la 
```js
let a;
```
Ceea ce ai facut tu se interpreteaza ca "Declara o variabila numita 'variabila' si apoi atribuie textul 'a' acelei variabile"

2022-10-17 06:33 UTC, cezarmocanu commented on tema1/script.js
> +a = 10;
Ca si informatie, problema de mai sus, duce la o problema aici si anume la faptul ca variabila ```a``` nu este declarata nicaieri(deoarece singura variabila declarata este ```variabila```).
In mod normal alte limbaje de programare nu ti-ar permite sa faci asta(specific, sa atribui o variabila care nu exista), dar JavaScript fiind compus din mai multe versiuni, iti permite, dar nu este corect, si trebuie sa avem grija la acest aspect

2022-10-17 06:33 UTC, cezarmocanu commented on tema1/script.js
> +console.log("a" + " " + "a fost declarat");
Aici era suficient 
```js
console.log("a a fost declarat");
```

2022-10-17 06:33 UTC, cezarmocanu commented on tema1/script.js
> +a += 1;
Foarte bine utilizat operatorul ```+=``` dar trebuie sa mentionez ca aceasta este o prescurtare de la 
```js
a = a + 1;
```

2022-10-17 06:33 UTC, cezarmocanu commented on tema1/script.js
> +console.log(`valoarea lui ${variabila} este ${variabila} = ${a}`);
Dupa ce rezolvi problema cu variabila de mai sus, poti modifica si aici astfel incat doar sa mentionezi variabila ca text
```
console.log(`Valoarea lui a este ${a}`);
```
respectiv
```js
console.log(`a are acum valoarea ${a}`);
```

2022-10-17 06:33 UTC, cezarmocanu commented on tema1/script2.js
> +console.log("EXERCITIUL 2");
Aceleasi mentiuni ca al exercitiul 1, te rog sa modifici

2022-10-17 06:33 UTC, cezarmocanu commented on tema1/script3.js
> +var a = "Luni";
Din nou mentinea de la exercitiul 1, legata utilizarea lui ```var``` si ```let```.

2022-10-17 06:33 UTC, cezarmocanu commented on tema1/script3.js
> +var a = "Marti";
Ceea ce ai facut tu aici se numeste redeclararea variabilei a (deoarece folosesti iar un declarator cum ar fi var(de preferat let)). Aceasta practica este gresita deoarece e ca si cum in loc sa schimbi continutul unui dulap, schimbi dulapul cu totul. Ar fi fost suficient sa atribui direct
```js
a = "Marti";
```

2022-10-17 06:33 UTC, cezarmocanu commented on tema1/script3.js
> +Luni = 0;
Din nou, ```Luni``` nu  exista ca variabila deoarece nu este declarata, exista variabila ```a``` care are valoarea ```"Luni"```.

2022-10-17 06:33 UTC, cezarmocanu commented on tema1/script3.js
> +
Per total, ai reusit sa faci algoritmul sa faca ce are de facut, dar as propune o solutie mai structurata care sa acopere problemele mentionate
```js
let indexLuni = 0;
let indexMarti = 1;
let indexMiercuri = 2;
let indexJoi = 3;
let indexVineri = 4;
let indexSambata = 5;
let indexDuminica = 6;

console.log(`Luni: ${indexLuni}`);
console.log(`Marti: ${indexMarti}`);
console.log(`Miercuri: ${indexMiercuri}`);
console.log(`Joi: ${indexJoi}`);
console.log(`Vineri: ${indexVineri}`);
console.log(`Sambata: ${indexSambata}`);
console.log(`Duminica: ${indexDuminica}`);
```

2022-10-17 06:33 UTC, cezarmocanu commented on tema1/script4.js
> +let a = "Nume";
Aici este bine ca am folosit let, dar din nou variabila ```Nume``` e nedeclarata, singura declarata este ```a``` si are ca valoare textul ```"Nume"```

2022-10-17 14:36 UTC, AdrianaGroza commented
Da, mi-am complicat existenta inutil pentru ca n-am inteles bine si am vrut cu tot dinadinsul sa NU apara a ca text  aici
console.log("a" + " " + "a fost declarat");
Multumesc, pentru comentarii, acum cred ca am inteles...

2022-10-18 11:32 UTC, cezarmocanu approved these changes

2022-10-18 11:32 UTC, cezarmocanu commented on tema1/script4.js
> +//let a; - nu mai este nevoie sa declar aceasta variabila deoarece am ales a ca in script.js, deci este declarata acolo
Este corect comentariul, ideal aici ar fi fost sa folosesti nume de variabile relevante la rpoblema cum ar fi nume si prenume

2022-10-18 11:32 UTC, merged