Andrei drg tema1
SkillBrain-com/Meteor-fe-g1-15-09-2022 pull request #31
Opened 2022-10-17 10:18 UTC by Andrei-drg

2022-10-17 11:08 UTC, cezarmocanu requested changes
Am lasat comentarii cu modificarile ce trebuie facute. 
- Mare atentie la ; la sfarsitul fiecarei instructiuni.
- Verifica daca algoritmul tau afiseaza in consola rezultatul pe care il astepti, in caz ca nu se intampla, cel mai probabil este algoritmul gresit
- Testeaza diferenta dintre '' si ``
- Urmareste un pic cum poti atribui valori unei variabile declarate, fara sa o redeclari folosind let

2022-10-17 11:08 UTC, cezarmocanu commented on Exercitii/index.js
> +//let a
Aici este suficient sa declaram variabila o singura data la inceputul programului, deoarece avem o singura instructiune de declarare. De asemenea nu uita de ; la sfarsitul fiecarei instructiuni

2022-10-17 11:08 UTC, cezarmocanu commented on Exercitii/index.js
> +//let a ="10"
Aici vrem sa ii atribuim variabilei a(care deja a fost declarata) o valoare(numerica) nu un mesaj. Astfel atribuirea va arata astfel
```js
a = 10;
```

2022-10-17 11:08 UTC, cezarmocanu commented on Exercitii/index.js
> +//const a = "20"
La fel ca mai sus

2022-10-17 11:08 UTC, cezarmocanu commented on Exercitii/index.js
> +//const a = "20"
De asemenea cuvantul ```const``` se foloseste in alt context, si il vom discuta ulterior, momentan folosim ```let``` si de asemenea, aici nu trebuie redeclarata variabila deoarece este declarata la prima instructiune

2022-10-17 11:08 UTC, cezarmocanu commented on Exercitii/index.js
> +console.log('valoarea lui a este ${a}')
Am mentionat ca pentru a putea face interpolarea(inlocuirea in text a variabilelor) trebuie sa folosim accentul(``) nu apostroful(''), deoarece au insemnatati diferite, iar instructiunea aceasta nu face ce trebuie sa faca

2022-10-17 11:08 UTC, cezarmocanu commented on Exercitii/index.js
> +console.log('valoarea lui a este ${a}')
Acceasi discutie cu `` vs ''

2022-10-17 11:08 UTC, cezarmocanu commented on Exercitii/index.js
> +let a = "a + 1"
Din nou, aici nu trebuie reatribuita variabila, ci doar trebuie sa assignam valoarea care exista inainte in variabila + 1, si anume
```js
a = a + 1; //acum a va avea valoarea precedenta + 1
```

2022-10-17 11:08 UTC, cezarmocanu commented on Exercitii/numele-meu.js
> +console.log("Numele meu este:")
Aici problema nu este completa, deoareace se va afisa doar textul "Numele meu este" iar cerinta indica ca trebuie si valoarea din variabile. Solutia in acest caz ar fi
```js
console.log(`Numele meu este: ${Nume} ${Prenume}`)
```

2022-10-17 11:08 UTC, cezarmocanu commented on Exercitii/script-scadere.js
> +
Aceleasi comentarii ca la exercitiul 1

2022-10-17 11:08 UTC, cezarmocanu commented on Exercitii/script-scadere.js
> +let b = "b + 5"
Aici ma astept la micsorarea variabilei cu 5 nu marirea

2022-10-17 11:08 UTC, cezarmocanu commented on Exercitii/script-zilele-saptamanii.js
> +console.log("Luni: 0")
Aici variabilele nu sunt folosite nicaieri, deoarece tu scrii textul pentru acestea. Rezolvarea ar fi sa afisezi mesajul urmat de valoarea variabilei corespunzatoare
```js
console.log(`Luni: ${Luni}`);
```

2022-10-17 11:08 UTC, cezarmocanu commented on Exercitii/index.html
> +
Scripturile momentan ar trebui sa le adaugam in body, ca si celelalte taguri

2022-10-17 12:13 UTC, Andrei-drg commented
Vaii ce de greșeli am😅, ma așteptam oricum sa am, pt ca nu am fost destul
de sigur cum se face, trebuia sa ma informez mai mult...

lun., 17 oct. 2022, 14:08 cezarmocanu ***@***.***> a scris:

> ***@***.**** requested changes on this pull request.
>
> Am lasat comentarii cu modificarile ce trebuie facute.
>
>    - Mare atentie la ; la sfarsitul fiecarei instructiuni.
>    - Verifica daca algoritmul tau afiseaza in consola rezultatul pe care
>    il astepti, in caz ca nu se intampla, cel mai probabil este algoritmul
>    gresit
>    - Testeaza diferenta dintre '' si ``
>    - Urmareste un pic cum poti atribui valori unei variabile declarate,
>    fara sa o redeclari folosind let
>
> ------------------------------
>
> In Exercitii/index.js
> <https://github.com/SkillBrain-com/Meteor-fe-g1-15-09-2022/pull/31#discussion_r996915829>
> :
>
> > @@ -0,0 +1,26 @@
> +
> +console.log("EXERCITIUL 1")
> +
> +//let a
>
> Aici este suficient sa declaram variabila o singura data la inceputul
> programului, deoarece avem o singura instructiune de declarare. De asemenea
> nu uita de ; la sfarsitul fiecarei instructiuni
> ------------------------------
>
> In Exercitii/index.js
> <https://github.com/SkillBrain-com/Meteor-fe-g1-15-09-2022/pull/31#discussion_r996916565>
> :
>
> > @@ -0,0 +1,26 @@
> +
> +console.log("EXERCITIUL 1")
> +
> +//let a
> +
> +console.log(" 'a' a fost declarat")
> +
> +console.log('valoarea lui a este ${a}')
> +
> +//let a ="10"
>
> Aici vrem sa ii atribuim variabilei a(care deja a fost declarata) o
> valoare(numerica) nu un mesaj. Astfel atribuirea va arata astfel
>
> a = 10;
>
> ------------------------------
>
> In Exercitii/index.js
> <https://github.com/SkillBrain-com/Meteor-fe-g1-15-09-2022/pull/31#discussion_r996916674>
> :
>
> > +
> +console.log("EXERCITIUL 1")
> +
> +//let a
> +
> +console.log(" 'a' a fost declarat")
> +
> +console.log('valoarea lui a este ${a}')
> +
> +//let a ="10"
> +
> +console.log("lui a i s-a atribuit 10")
> +
> +console.log('valoarea lui a este ${a}')
> +
> +//const a = "20"
>
> La fel ca mai sus
> ------------------------------
>
> In Exercitii/index.js
> <https://github.com/SkillBrain-com/Meteor-fe-g1-15-09-2022/pull/31#discussion_r996918342>
> :
>
> > +
> +console.log(" 'a' a fost declarat")
> +
> +console.log('valoarea lui a este ${a}')
> +
> +//let a ="10"
> +
> +console.log("lui a i s-a atribuit 10")
> +
> +console.log('valoarea lui a este ${a}')
> +
> +//const a = "20"
> +
> +console.log("a si-a schimbat valoarea")
> +
> +console.log('valoarea lui a este ${a}')
>
> Am mentionat ca pentru a putea face interpolarea(inlocuirea in text a
> variabilelor) trebuie sa folosim accentul(``) nu apostroful(''), deoarece
> au insemnatati diferite, iar instructiunea aceasta nu face ce trebuie sa
> faca
> ------------------------------
>
> In Exercitii/index.js
> <https://github.com/SkillBrain-com/Meteor-fe-g1-15-09-2022/pull/31#discussion_r996919261>
> :
>
> > +
> +console.log("lui a i s-a atribuit 10")
> +
> +console.log('valoarea lui a este ${a}')
> +
> +//const a = "20"
> +
> +console.log("a si-a schimbat valoarea")
> +
> +console.log('valoarea lui a este ${a}')
> +
> +let a = "a + 1"
> +
> +console.log("a si-a marit valoarea cu 1")
> +
> +console.log('valoarea lui a este ${a}')
>
> Acceasi discutie cu `` vs ''
> ------------------------------
>
> In Exercitii/index.js
> <https://github.com/SkillBrain-com/Meteor-fe-g1-15-09-2022/pull/31#discussion_r996919900>
> :
>
> > +
> +console.log('valoarea lui a este ${a}')
> +
> +//let a ="10"
> +
> +console.log("lui a i s-a atribuit 10")
> +
> +console.log('valoarea lui a este ${a}')
> +
> +//const a = "20"
> +
> +console.log("a si-a schimbat valoarea")
> +
> +console.log('valoarea lui a este ${a}')
> +
> +let a = "a + 1"
>
> Din nou, aici nu trebuie reatribuita variabila, ci doar trebuie sa
> assignam valoarea care exista inainte in variabila + 1, si anume
>
> a = a + 1; //acum a va avea valoarea precedenta + 1
>
> ------------------------------
>
> In Exercitii/numele-meu.js
> <https://github.com/SkillBrain-com/Meteor-fe-g1-15-09-2022/pull/31#discussion_r996921385>
> :
>
> > @@ -0,0 +1,10 @@
> +console.log("EXERCITIUL 4")
> +
> +let Nume = "Andrei"
> +
> +let Prenume = "Dragomir"
> +
> +
> +console.log("Numele meu este:")
>
> Aici problema nu este completa, deoareace se va afisa doar textul "Numele
> meu este" iar cerinta indica ca trebuie si valoarea din variabile. Solutia
> in acest caz ar fi
>
> console.log(`Numele meu este: ${Nume} ${Prenume}`)
>
> ------------------------------
>
> In Exercitii/script-scadere.js
> <https://github.com/SkillBrain-com/Meteor-fe-g1-15-09-2022/pull/31#discussion_r996921610>
> :
>
> > @@ -0,0 +1,25 @@
> +console.log('EXERCITIUL 2')
> +
>
> Aceleasi comentarii ca la exercitiul 1
> ------------------------------
>
> In Exercitii/script-scadere.js
> <https://github.com/SkillBrain-com/Meteor-fe-g1-15-09-2022/pull/31#discussion_r996921808>
> :
>
> > +
> +console.log('valoarea lui b este ${b}')
> +
> +//let b ="10"
> +
> +console.log("lui b i s-a atribuit 10")
> +
> +console.log('valoarea lui b este ${b}')
> +
> +//let b = "20"
> +
> +console.log("b si-a schimbat valoarea")
> +
> +console.log('valoarea lui a este ${b}')
> +
> +let b = "b + 5"
>
> Aici ma astept la micsorarea variabilei cu 5 nu marirea
> ------------------------------
>
> In Exercitii/script-zilele-saptamanii.js
> <https://github.com/SkillBrain-com/Meteor-fe-g1-15-09-2022/pull/31#discussion_r996923133>
> :
>
> > @@ -0,0 +1,29 @@
> +console.log('EXERCITIUL 3')
> +
> +let Luni = "0"
> +
> +console.log("Luni: 0")
>
> Aici variabilele nu sunt folosite nicaieri, deoarece tu scrii textul
> pentru acestea. Rezolvarea ar fi sa afisezi mesajul urmat de valoarea
> variabilei corespunzatoare
>
> console.log(`Luni: ${Luni}`);
>
> ------------------------------
>
> In Exercitii/index.html
> <https://github.com/SkillBrain-com/Meteor-fe-g1-15-09-2022/pull/31#discussion_r996923856>
> :
>
> > @@ -0,0 +1,16 @@
> +<!DOCTYPE html>
> +<html lang="en">
> +<head>
> +    <meta charset="UTF-8">
> +    <meta http-equiv="X-UA-Compatible" content="IE=edge">
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0">
> +    <title>Document</title>
> +</head>
> +<body>
> +
>
> Scripturile momentan ar trebui sa le adaugam in body, ca si celelalte
> taguri
> ------------------------------
>
> In Exercitii/index.js
> <https://github.com/SkillBrain-com/Meteor-fe-g1-15-09-2022/pull/31#discussion_r996917438>
> :
>
> > +
> +console.log("EXERCITIUL 1")
> +
> +//let a
> +
> +console.log(" 'a' a fost declarat")
> +
> +console.log('valoarea lui a este ${a}')
> +
> +//let a ="10"
> +
> +console.log("lui a i s-a atribuit 10")
> +
> +console.log('valoarea lui a este ${a}')
> +
> +//const a = "20"
>
> De asemenea cuvantul const se foloseste in alt context, si il vom discuta
> ulterior, momentan folosim let si de asemenea, aici nu trebuie
> redeclarata variabila deoarece este declarata la prima instructiune
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/SkillBrain-com/Meteor-fe-g1-15-09-2022/pull/31#pullrequestreview-1143945086>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A2X7T54LN7ULVHIJJHZYO3DWDUXTXANCNFSM6AAAAAARG5HDRE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***
> com>
>

2022-10-23 11:08 UTC, cezarmocanu requested changes

2022-10-23 11:08 UTC, cezarmocanu commented on Exercitii/numele-meu.js
> +console.log("Numele meu este: Dragomir Andrei")
Aici afisezi mesajul, dar nu foloseti variabilele, te rog  sa modifici astfel incat sa afisezi numele folosind valoarea din variabile, astfel incat daca modifici valoarea variabilelor mesajul modificat se va modifica automat.
```js
console.log(`Numele meu este ${Nume} ${Prenume}`);
```

2022-10-25 08:14 UTC, cezarmocanu approved these changes

2022-10-25 08:14 UTC, merged