Tema-1
SkillBrain-com/Meteor-fe-g1-15-09-2022 pull request #32
Opened 2022-10-17 16:42 UTC by ovidiufilip10

Nivel 1

2022-10-17 19:44 UTC, cezarmocanu requested changes
Abordarea e buna, a rezolvat problema, astept si urmatoarele nivele pana cand te blochezi la unul din ele. De asemenea o sa te rog sa imbunatatesti partea de nesting pentur a face codul mai lizibil

2022-10-17 19:44 UTC, cezarmocanu commented on Tema1/nivel1.js
> +for(let counter = 1; counter <= number; counter++)
In javascript parantezele se scriu dupa conventia de mai jos
```js
code {

}
```
spre deosebire de c++ unde sunt scrise
```
code 
{

}
```

2022-10-17 19:44 UTC, cezarmocanu commented on Tema1/nivel1.js
> +for(let counter = 1; counter <= number; counter++)
Ca si imbunatatire recomand sa identifici unde poti sa reduci nestingul la cod, de exemplu aici puteai sa faci in felul urmator
```js
for(let i=1; i<= 100;i++){
  if(counter % 15 === 0) {
    console.log("FizzBuzz");
    continue;
  }
  
  if(counter % 5 === 0) {
    console.log("Buzz");
    continue;
  }
  
  if(counter % 3 === 0) {
    console.log("Fizz");
    continue;
  }
}
```

De asemenea partea de aplicare a regulii de impartire puteai sa o faci intr-o functie separata

```js
function applyRules(nr){
  if(nr % 15  === 0){
    console.log("FizzBuzz");
    return;
  }
  
  ...
}
```

2022-10-20 15:33 UTC, ovidiufilip10 commented on Tema1/nivel1.js
> +for(let counter = 1; counter <= number; counter++)
Am modificat structura si algoritmul.

2022-10-28 18:48 UTC, cezarmocanu requested changes
Astept problema 3

2022-10-28 18:48 UTC, cezarmocanu commented on Tema 2/nivel2.js
> +const output = [];
Folosind un dictionar putem face ceva mai interesant pt n numere.
```js
const counters = {};
for(let i=0;i<input.length;i++){

//in caz ca o valoarea nu exista in dictionar
  if(counters[input[i]] === unefined) {
    counters[input[i]] = 0; //initializam valoarea cu 0
  }
  
  counters[input[i]]++  
}

const sortedKeys = Object.keys(counters).sort();
for (let i=0;i<sortedKeys.length;i++){
  const key =sortedKeys[i];
  console.log(`${key} - ${counters[key]}`) 
}
```

2022-11-01 18:22 UTC, cezarmocanu approved these changes

2022-11-03 06:07 UTC, merged