Ale barboni tema 1
SkillBrain-com/Meteor-fe-g1-15-09-2022 pull request #36
Opened 2022-10-18 15:48 UTC by AleBarboni

2022-10-18 16:09 UTC, cezarmocanu requested changes

2022-10-18 16:09 UTC, cezarmocanu commented on JS/Tema 1/script-numele-meu-este.js
> +console.log("Numele meu este:", nume, prenume);
```js
console.log(`Numele meu este ${nume} ${prenume}`)
```

2022-10-18 16:09 UTC, cezarmocanu commented on JS/Tema 1/script-scadere.js
> +console.log("valoarea lui b este ${b}");
Interpolare in loc de text

2022-10-18 16:09 UTC, cezarmocanu commented on JS/Tema 1/script-scadere.js
> +b = b - 5;
Echivalent cu

```js
b -= 5;
```

Alte exemple
```js
b += 5; //isi  mareste valoarea cu 5
b *= 5; // b = b * 5;
b /= 5; // b = b / 5;
b %= 5; // b = b % 5;
```

2022-10-18 16:09 UTC, cezarmocanu commented on JS/Tema 1/script.js
> +console.log("valoarea lui a este ${a}");
Te rog sa completezi exercitiul

2022-10-19 15:11 UTC, AleBarboni commented on JS/Tema 1/script-scadere.js
> +console.log("valoarea lui b este ${b}");
done

2022-10-19 15:11 UTC, AleBarboni commented on JS/Tema 1/script-scadere.js
> +b = b - 5;
done

2022-10-19 15:11 UTC, AleBarboni commented on JS/Tema 1/script.js
> +console.log("valoarea lui a este ${a}");
done

2022-10-20 08:36 UTC, cezarmocanu approved these changes

2022-10-20 08:36 UTC, cezarmocanu commented on JS/Tema-1-avansati/script3.js
> +const countOccurrences = function(arr, val) {
Buna rezolvare, apreciez ca ai cautat solutii, dar esential la o solutie e sa si intelegi conceptele aplicate. De asemenea rezolvarea acopera doar cifrele impare la de 1 la 9 dar trebuie sa fie aplicabile pentru toate numerele.

Las aici o varianta de rezolvare, si cateva concepte cheie pe care vrei sa le cauti

```js
// acesta este un jsol (javascript object literal) care are rolul unui doctionar
// dictionar deoarece stocheaza informatia sub forma de cheie - valoare
let occurenceMap = {}; 

//trecem prin fiecare numar din lista
for (let i=0; i < allNumbers.length;i++){
  let number = allNumbers[i]; // selectam pe rand fiecare numar din lista
  
  // daca valoarea dictionarului la o anumita cheie este undefined
  // inseamna ca nu am gasit aceea valoare pana acum
  // si asta ar fi prima aparitie
  if ( occurenceMap[number] === undefined) {
    occurenceMap[number] = 1;
    continue;//trecem la pasul urmator din bucla si ignoram restul instructiunilor
  }
  
  //daca am ajuns aici inseamna ca deja exista cheia respectiva
  //adica deja am intalnit acel numar
  occurenceMap[number] += 1; // marim numarul de aparitii de la aceea poztie cu 1
}

//extragem cheile din dinctionarul nostru si le sortam crescator
const sortedKeys = Object.keys(occurenceMap).sort();

for (let i = 0; i < sortedKeys.length; i++){
  let key = sortedKeys[i]; // selectam fiecare cheie pe rand
  let occurenceCount = occurenceMap[key]; // extragem numarul de aparitii
  console.log(`${key} - ${occurenceCount} aparitii`;
}
```

2022-10-20 08:36 UTC, cezarmocanu commented on JS/Tema-1-avansati/index2.html
> +<!DOCTYPE html>
De asemenea as fi vrut ca tema de avansati sa o faci pe alt branch astfel incat sa pot da merge la branch-ul asta

2022-10-20 08:36 UTC, cezarmocanu commented
Pentru urmatoarele teme, cand schimbi subiectul pe care lucrezi/ taskul o sa te rog sa iti faci un branch nou astfel incat sa putem lucra organizat

2022-10-20 08:37 UTC, merged