First commit
SkillBrain-com/Meteor-fe-g1-15-09-2022 pull request #39
Opened 2022-10-18 16:46 UTC by lucyroom

2022-10-19 08:59 UTC, cezarmocanu requested changes

2022-10-19 08:59 UTC, cezarmocanu commented on Javascript-1/script4.js
> +let nume = ("Bogdan");
aici nu este nevoie de paranteze in jurul textului, textul se diferentiaza doar prin "" cum ar fi ```"Bogdan"```

2022-10-19 08:59 UTC, cezarmocanu commented on Javascript-1/script4.js
> +console.log("Numele meu este: " + nume + " " + prenume);
Am vazut ca peste tot ai folosit concatenarea, singura completarea ar fi sa incerci sa modifici astfel incat sa folosesti acel string template sau interpolarea variabilelor in text, sa vezi cum functioneaza.
```js
console.log(`Numele meu este: ${nume} ${prenume}`);
```

2022-10-19 09:10 UTC, lucyroom commented on Javascript-1/script4.js
> +console.log("Numele meu este: " + nume + " " + prenume);
Am folosit concatenarea pentru ca altfel nu imi dadea rezultatul.
 Rezultatul final asa imi arata
EXERCITIUL 4
Numele meu este: ${ nume } ${ prenume }.

2022-10-20 08:06 UTC, cezarmocanu approved these changes

2022-10-20 08:08 UTC, merged