Ale barboni tema 2
SkillBrain-com/Meteor-fe-g1-15-09-2022 pull request #42
Opened 2022-10-22 14:56 UTC by AleBarboni

2022-10-22 16:02 UTC, cezarmocanu requested changes
Astept exercitiile urmatorare

2022-10-22 16:02 UTC, cezarmocanu commented on JS/Tema 2 - Structura decizionala/script.js
> +
singura mentiune e ca aici nu ar fi trebuit spatiul dupa blocul de la if, astfel incat sa ne dam seama ca else-ul este legat de acest if

2022-10-23 10:01 UTC, cezarmocanu requested changes

2022-10-23 10:01 UTC, cezarmocanu commented on JS/Tema 2 - Structura decizionala/script2.js
> +    if(n >= 0 && n < 100) {
Super rezolvare, singura modificare e ca as scoate indentarea din stanga conditilor si nu as lasa spatiu intre if si else

2022-10-23 10:01 UTC, cezarmocanu commented
Pana aici all good astept urmatoarele exercitii 💪

2022-10-23 13:27 UTC, AleBarboni commented
Tema 2

2022-10-23 15:03 UTC, cezarmocanu requested changes
Super 💪

2022-10-23 15:03 UTC, cezarmocanu approved these changes

2022-10-23 15:03 UTC, merged