Ale barboni tema 3
SkillBrain-com/Meteor-fe-g1-15-09-2022 pull request #58
Opened 2022-10-30 05:29 UTC by AleBarboni

2022-10-30 10:57 UTC, cezarmocanu requested changes

2022-10-30 10:57 UTC, cezarmocanu commented on JS/Tema 3 - Structura iterativa si listele/script-pretul-mediu.js
> +const avgCarBuyPriceRounded = Math.ceil(avgCarBuyPrice);
Intereasanta abrodare, atata sa ai in vedere ca Math.ceil rotunjeste cu precadere la urmatoarea valoare, Math.floor rejunjeste spre valaorea precedenta, si Math.round ar fi cea mai neinfluentata rotunjire, respectiv cea mai corecta

2022-10-30 10:57 UTC, cezarmocanu commented on JS/Tema 3 - Structura iterativa si listele/script-car-transmition.js
> +
Fisierul asta e posibil sa fie in plus, o sa te rog sa il stergi

2022-10-30 10:57 UTC, cezarmocanu commented on JS/Tema 3 - Structura iterativa si listele/script-pretul-min-si-max.js
> +for(i = 0; i < carBuyPrice2.length; i++) {
Ca sa rezolvam problema maximului:

- declaram o variabila (maxPrice) pe care o initializam cu primul element din lista
- parcurgem fiecare element cu un iterator i
  -->daca elementul la care suntem (lista[i]) este mai mare decat maxPrice atunci maxPrice preia valoarea de la lista[i]
  -->daca nu nu facem nimic(adica e doar un if, fara else)
- dupa ce am parcurs toata lista afisam max-ul
Avem si in cursul de joi, temperatura maxima dedusa in stilul asta

2022-10-30 10:57 UTC, cezarmocanu commented on JS/Tema 3 - Structura iterativa si listele/script-car-transmission.js
> +    if( i === "Manuala") {
Aici i ia valori de la 0 la carTransmission.length. Ce poti face sa vizualizezi informatia este sa pui un console.log(i) in for, sa vezi ce valori are. Ce e intereseaza pe tine este sa folosesti elementul al i-lea din lista carTransmission[i]

2022-10-30 10:57 UTC, cezarmocanu commented on JS/Tema 3 - Structura iterativa si listele/script-car-transmission.js
> +    manualTransmission += manualTransmission;
aici vrem sa marim cu 1, fiindca manualTransmission este initial 0 si practic o sa facem 0+0+0+0+...+0

2022-10-31 19:18 UTC, AleBarboni commented
tema 3 JS

2022-11-06 09:43 UTC, cezarmocanu approved these changes
Great work 💪

2022-11-06 09:43 UTC, cezarmocanu commented on JS/Tema 3 - Structura iterativa si listele/script-car-transmission.js
> +let manualTrasmission = 0;
Aici este o greseala care poate duce la comportamente neprevăzute. Ai initializat variabila manualTransmission cu 0, ceea ce mie ca programator imi spune ca ma astept sa reprezinte un numar(continuarea mai jos)

2022-11-06 09:43 UTC, cezarmocanu commented on JS/Tema 3 - Structura iterativa si listele/script-car-transmission.js
> +   const manualTrasmission = carTransmission[i];
Dar aici ai redefinit variabila ca fiind o constanta in care atribuiai pe rand fiecare element din lista, si asta ma face confuz

2022-11-06 09:43 UTC, cezarmocanu commented on JS/Tema 3 - Structura iterativa si listele/script-car-transmission.js
> +   const automaticTransmission = carTransmission[i];
si aici ai reatribuit fiecare element in alta variabila pe care ai redefinit-o din numar in altceva

2022-11-06 09:43 UTC, cezarmocanu commented on JS/Tema 3 - Structura iterativa si listele/script-car-transmission.js
> +   if(manualTrasmission === "Manuala") {
As vedea codul in felul urmator

```js
//definim doua contoare

for(...){
   const transmission = transmissionList[i];
   
  if (transmission === "Automat"){
    //marim contorul la automat
  }

  if (transmission === "Manuala"){
    //marim contorul la manual
  }
}

```

2022-11-06 09:43 UTC, cezarmocanu commented on JS/Tema 3 - Structura iterativa si listele/script-pretul-min-si-max.js
> +let minPrice = Infinity;
e buna abordarea, dar putem initializa cu primul element din lista si nu ne bazam pe - si + infinit

2022-11-06 09:43 UTC, cezarmocanu commented on JS/Tema 3 - Structura iterativa si listele/script-pretul-min-si-max.js
> +for (let number of carBuyPrice2) {
atentie la operatorul of, scopul lui e sa itereze fiecare element din lista ca si o varaiabila constanta

Aici ar fi fost 
```js
for (cont pretCumparare of carBuyPrice){}

```

2022-11-06 09:43 UTC, cezarmocanu commented on JS/Tema 3 - Structura iterativa si listele/script-pretul-min-si-max.js
> +for (let number of carBuyPrice2) {
de asemenea atentie fiindca poate fi condundar si cu operatorul for in

2022-11-06 09:43 UTC, cezarmocanu commented on JS/Tema 3 - Structura iterativa si listele/script-pretul-min-si-max.js
> +    console.log(`Cea mai scumpa masina este ${carMake2[carBuyPrice2.indexOf(maxPrice)]} ${carModel2[carBuyPrice2.indexOf(maxPrice)]} si costa ${carBuyPrice2[carBuyPrice2.indexOf(maxPrice)]}.`);
Buna abordarea, atata trebuie sa tii cont ca indexOf mai trece inca o data prin lista pt fiecare apel, astfel tu aici parcurgi lista de 6 ori doar ca sa afisezi doua randuri de text.

Ce putem face este sa initializam doua variabile inainte de for, indexMin, indexMax, le pornim de la 0 si cand gasim o valoare mai mare ca maximul/mai mica ca minimul salvam valoarea si pe langa asta salvam si i(indexul/pozitia) la care se afla acel element

la final poti zice lista[indexMax]

2022-11-06 09:43 UTC, cezarmocanu commented on JS/Tema 3 - Structura iterativa si listele/script-profit.js
> +    profit = SellPrice[i] - BuyPrice[i];
aici meregea sa foloesti direct ```const profit``` fiindca variabila profit nu este folosita in afara for-ului

2022-11-06 09:43 UTC, merged